import "./globals.css";

export const metadata = {
  title: "PulseTimer",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/sonner";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
